openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: API для работы с заказами
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Операции с данными о заказах

paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/get_order.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/pay_order.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/cancel_order.yaml
