services:

  postgres-order:
    image: postgres:17.0-alpine3.20
    
    container_name: postgres-order

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_order_data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - rocket_science_network

volumes:
  postgres_order_data:

networks:
  rocket_science_network:
    external: true
