services:
  mongo-inventory:
    image: mongo:7.0.5
    container_name: mongo-inventory

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "${MONGO_PORT}:27017"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - rocket_science_network

volumes:
  mongo_inventory_data:
  
networks:
  rocket_science_network:
    external: true
